<?php defined('BASEPATH') OR exit('No direct script access allowed');

/*
|--------------------------------------------------------------------------
| Base Site URL
|--------------------------------------------------------------------------
|
| URL to your CodeIgniter root. Typically this will be your base URL,
| WITH a trailing slash:
|
|    http://example.com/
|
| If this is not set then CodeIgniter will guess the protocol, domain and
| path to your installation.
|
*/
// Build base_url from the public-facing host/scheme. Prefer X-Forwarded-* so
// tunnels (Expose, ngrok) and TLS-terminating reverse proxies render links
// that resolve from the outside, not the internal Herd/.test hostname.
// Falls back to HTTP_HOST + HTTPS when the forwarded headers aren't set.
// Note: a production install that accepts Host-header overrides from
// untrusted clients should populate $config['proxy_ips'] and add stricter
// trust — this block intentionally trusts whatever set the headers.
$pyro_fwd_host  = isset($_SERVER['HTTP_X_FORWARDED_HOST'])  ? trim(strtok($_SERVER['HTTP_X_FORWARDED_HOST'], ',')) : '';
$pyro_fwd_proto = isset($_SERVER['HTTP_X_FORWARDED_PROTO']) ? strtolower(trim(strtok($_SERVER['HTTP_X_FORWARDED_PROTO'], ','))) : '';
$pyro_host      = $pyro_fwd_host !== '' ? $pyro_fwd_host : (isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : '');
$pyro_scheme    = $pyro_fwd_proto !== '' ? $pyro_fwd_proto : ((isset($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) === 'on') ? 'https' : 'http');

$config['base_url'] = $pyro_host !== '' ? $pyro_scheme . '://' . $pyro_host . '/' : '';

unset($pyro_fwd_host, $pyro_fwd_proto, $pyro_host, $pyro_scheme);

// Bockavel registered SMS recipients — sourced from .env (SMS_REGISTERED).
// Format: comma-separated <name>:<phone> pairs. See .env.*.example.
$config['sms_registered'] = array();
foreach (env_list('SMS_REGISTERED') as $entry) {
    if (strpos($entry, ':') === false) continue;
    list($name, $phone) = array_map('trim', explode(':', $entry, 2));
    if ($name !== '' && $phone !== '') {
        $config['sms_registered'][$name] = $phone;
    }
}

// Password-protected folders (File Manager folder names, case-sensitive).
// Sourced from .env (PROTECTED_FOLDERS). The fallback is the full known list
// so we fail closed if PROTECTED_FOLDERS is accidentally unset.
$config['protected_folders'] = env_list('PROTECTED_FOLDERS', array(
    'safe', 'member',
    'medlem_seminbockar', 'medlem_video',
    'medlem_dokument', 'medlem_dokument_2022',
    'medlem_bilder', 'medlem_2019',
    'medlem_2023', 'medlem_2024', 'medlem_2025', 'medlem_2026',
));
/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'            Default - auto detects
| 'PATH_INFO'        Uses the PATH_INFO
| 'QUERY_STRING'    Uses the QUERY_STRING
| 'REQUEST_URI'        Uses the REQUEST_URI
| 'ORIG_PATH_INFO'    Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']    = 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']    = "english"; // Is overridden in hooks/pick_language.php

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';

/*
|--------------------------------------------------------------------------
| Enable/Disable System Hooks
|--------------------------------------------------------------------------
|
| If you would like to use the 'hooks' feature you must enable it by
| setting this variable to true (boolean).  See the user guide for details.
|
*/
$config['enable_hooks'] = true;


/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';


/*
|--------------------------------------------------------------------------
| Allowed URL Characters
|--------------------------------------------------------------------------
|
| This lets you specify with a regular expression which characters are permitted
| within your URLs.  When someone tries to submit a URL with disallowed
| characters they will get a warning message.
|
| As a security measure you are STRONGLY encouraged to restrict URLs to
| as few characters as possible.  By default only these are allowed: a-z 0-9~%.:_-
|
| Leave blank to allow all characters -- but only if you are insane.
|
| DO NOT CHANGE THIS UNLESS YOU FULLY UNDERSTAND THE REPERCUSSIONS!!
|
*/
$config['permitted_uri_chars'] = 'a-z 0-9~%.:_\-';


/*
|--------------------------------------------------------------------------
| Enable Query Strings
|--------------------------------------------------------------------------
|
| By default CodeIgniter uses search-engine friendly segment based URLs:
| example.com/who/what/where/
|
| By default CodeIgniter enables access to the $_GET array.  If for some
| reason you would like to disable it, set 'allow_get_array' to false.
|
| You can optionally enable standard query string based URLs:
| example.com?who=me&what=something&where=here
|
| Options are: true or false (boolean)
|
| The other items let you set the query string 'words' that will
| invoke your controllers and its functions:
| example.com/index.php?c=controller&m=function
|
| Please note that some of the helpers won't work as expected when
| this feature is enabled, since CodeIgniter is designed primarily to
| use segment based URLs.
|
*/
$config['allow_get_array']        = true;
$config['enable_query_strings'] = false;
$config['controller_trigger']    = 'c';
$config['function_trigger']        = 'm';
$config['directory_trigger']    = 'd'; // experimental not currently in use

/*
|--------------------------------------------------------------------------
| Error Logging Threshold
|--------------------------------------------------------------------------
|
| If you have enabled error logging, you can set an error threshold to
| determine what gets logged. Threshold options are:
| You can enable error logging by setting a threshold over zero. The
| threshold determines what gets logged. Threshold options are:
|
|    0 = Disables logging, Error logging TURNED OFF
|    1 = Error Messages (including PHP errors)
|    2 = Debug Messages
|    3 = Informational Messages
|    4 = All Messages
|
| You can also pass in a array with threshold levels to show individual error types
|
|     array(2) = Debug Messages, without Error Messages
|
| For a live site you'll usually only enable Errors (1) to be logged otherwise
| your log files will fill up very fast.
|
*/
$config['log_threshold'] = 1;

/*
|--------------------------------------------------------------------------
| Error Logging Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cms/logs/ folder. Use a full server path with trailing slash.
|
*/
$config['log_path'] = '';

/*
|--------------------------------------------------------------------------
| Date Format for Logs
|--------------------------------------------------------------------------
|
| Each item that is logged has an associated date. You can use PHP date
| codes to set your own date formatting
|
*/
$config['log_date_format'] = 'Y-m-d H:i:s';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/

// This is set in the pyrocache config so Pro can set the correct SITE_REF
$config['cache_path'] = '';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
// Read from ENCRYPTION_KEY in .env / real environment. Fail-closed: a
// mis-provisioned host should show an error page, not silently run with an
// empty key and produce broken session cookies / unverifiable CSRF tokens.
$config['encryption_key'] = env_str('ENCRYPTION_KEY');
if ($config['encryption_key'] === '') {
    show_error('ENCRYPTION_KEY is not configured. Set it in .env.', 500);
}

/*
|--------------------------------------------------------------------------
| Session Variables
|--------------------------------------------------------------------------
|
| 'sess_cookie_name'        = the name you want for the cookie
| 'sess_expiration'            = the number of SECONDS you want the session to last.
|   by default sessions last 7200 seconds (two hours).  Set to zero for no expiration.
| 'sess_expire_on_close'    = Whether to cause the session to expire automatically
|   when the browser window is closed
| 'sess_encrypt_cookie'        = Whether to encrypt the cookie
| 'sess_use_database'        = Whether to save the session data to a database
| 'sess_table_name'            = The name of the session database table
| 'sess_match_ip'            = Whether to match the user's IP address when reading the session data
| 'sess_match_useragent'    = Whether to match the User Agent when reading the session data
| 'sess_time_to_update'        = how many seconds between CI refreshing Session Information
|
*/
$config['sess_driver']             = 'files';
$config['sess_cookie_name']        = 'pyrocms' . (ENVIRONMENT !== 'production' ? '_' . ENVIRONMENT : '');
// Use a positive expiration so the session file persists across requests.
// sess_expire_on_close still applies to the browser cookie lifetime.
$config['sess_expiration']         = 7200;
$config['sess_expire_on_close']    = false;
// CI 3.1 ignores sess_encrypt_cookie; file sessions store data server-side.
$config['sess_use_database']       = false;
$config['sess_table_name']         = 'default_ci_sessions';
$config['sess_save_path']          = FCPATH.'system/cms/cache/sessions';
// The original comment disabled these due to session churn from the
// pick_language pre_controller hook. That hook now aligns the session cookie
// name with CI's sess_cookie_name before session_start() (see
// system/cms/hooks/pick_language.php), so the hand-off is stable and we can
// enforce binding again.
//
// sess_match_useragent is cheap and catches cookie theft across devices.
// sess_match_ip is strict and can churn on mobile / proxied traffic — keep
// it off unless you've verified your deploy sees a stable REMOTE_ADDR.
$config['sess_match_ip']           = false;
$config['sess_match_useragent']    = true;
$config['sess_time_to_update']     = 300;
$config['sess_regenerate_destroy'] = false;

/*
|--------------------------------------------------------------------------
| Cookie Related Variables
|--------------------------------------------------------------------------
|
| 'cookie_prefix' = Set a prefix if you need to avoid collisions
| 'cookie_domain' = Set to .your-domain.com for site-wide cookies
| 'cookie_path'   =  Typically will be a forward slash
| 'cookie_secure' =  Cookies will only be set if a secure HTTPS connection exists.
|
*/
// for multi-site logins to work properly we have to set a prefix. We use the subdomain for that or default_ if none exists.
$config['cookie_prefix']    = (substr_count($_SERVER['SERVER_NAME'], '.') > 1) ? substr($_SERVER['SERVER_NAME'], 0, strpos($_SERVER['SERVER_NAME'], '.')) . '_' : 'default_';
$config['cookie_domain']    = ($_SERVER['SERVER_NAME'] == 'localhost') ? '' : $_SERVER['SERVER_NAME'];
$config['cookie_path']        = BASE_URI;
// Force Secure cookies in production, and opportunistically when HTTPS is
// detected (e.g. behind a TLS-terminating proxy that sets $_SERVER['HTTPS']).
$config['cookie_secure']    = (ENVIRONMENT === PYRO_PRODUCTION)
                              || ( ! empty($_SERVER['HTTPS']) && strtolower($_SERVER['HTTPS']) !== 'off');
$config['cookie_httponly']  = true;
// CI 3.1 honours this; CI 2.x ignores it safely.
$config['cookie_samesite']  = 'Lax';

/*
|--------------------------------------------------------------------------
| Global XSS Filtering
|--------------------------------------------------------------------------
|
| Determines whether the XSS filter is always active when GET, POST or
| COOKIE data is encountered
|
*/
$config['global_xss_filtering'] = false;

/*
|--------------------------------------------------------------------------
| Cross Site Request Forgery
|--------------------------------------------------------------------------
| Enables a CSRF cookie token to be set. When set to true, token will be
| checked on a submitted form. If you are accepting user data, it is strongly
| recommended CSRF protection be enabled.
|
| 'csrf_token_name' = The token name
| 'csrf_cookie_name' = The cookie name
| 'csrf_expire' = The number in seconds the token should expire.
| 'csrf_exclude_uris' = Array of URIs which ignore CSRF checks
*/
$config['csrf_protection']         = true;
// Don't regenerate the token on every request — breaks AJAX / multi-tab flows.
$config['csrf_regenerate']         = false;
$config['csrf_token_name']         = 'csrf_hash_name';
$config['csrf_cookie_name']        = 'csrf_cookie_name';
$config['csrf_expire']             = 7200;
// Add pure read-only APIs or external webhooks here (regex patterns).
$config['csrf_exclude_uris']       = array();

/*
|--------------------------------------------------------------------------
| Output Compression
|--------------------------------------------------------------------------
|
| Enables Gzip output compression for faster page loads.  When enabled,
| the output class will test whether your server supports Gzip.
| Even if it does, however, not all browsers support compression
| so enable only if you are reasonably sure your visitors can handle it.
|
| VERY IMPORTANT:  If you are getting a blank page when compression is enabled it
| means you are prematurely outputting something to your browser. It could
| even be a line of whitespace at the end of one of your scripts.  For
| compression to work, nothing can be sent before the output buffer is called
| by the output class.  Do not 'echo' any values with compression enabled.
|
*/
$config['compress_output'] = false;

/*
|--------------------------------------------------------------------------
| Minify
|--------------------------------------------------------------------------
|
| Removes extra characters (usually unnecessary spaces) from your
| output for faster page load speeds.  Makes your outputted HTML source
| code less readable.
|
*/
$config['minify_output'] = (ENVIRONMENT !== PYRO_DEVELOPMENT); // only do this on

/*
|--------------------------------------------------------------------------
| Master Time Reference
|--------------------------------------------------------------------------
|
| Options are 'local' or 'gmt'.  This pref tells the system whether to use
| your server's local time as the master 'now' reference, or convert it to
| GMT.  See the 'date helper' page of the user guide for information
| regarding date handling.
|
*/
$config['time_reference'] = 'gmt';


/*
|--------------------------------------------------------------------------
| Rewrite PHP Short Tags
|--------------------------------------------------------------------------
|
| If your PHP installation does not have short tag support enabled CI
| can rewrite the tags on-the-fly, enabling you to utilize that syntax
| in your view files.  Options are true or false (boolean)
|
*/
$config['rewrite_short_tags'] = false;


/*
|--------------------------------------------------------------------------
| Reverse Proxy IPs
|--------------------------------------------------------------------------
|
| If your server is behind a reverse proxy, you must whitelist the proxy IP
| addresses from which CodeIgniter should trust the HTTP_X_FORWARDED_FOR
| header in order to properly identify the visitor's IP address.
| Comma-delimited, e.g. '10.0.1.200,10.0.1.201'
|
*/
$config['proxy_ips'] = '';


/*
|--------------------------------------------------------------------------
| Module Locations
|--------------------------------------------------------------------------
|
| Modular Extensions: Where are modules located?
|
*/
$config['modules_locations'] = array(
    APPPATH.'modules/' => '../modules/',
    ADDON_FOLDER.'__SITE_REF__/modules/' => '../../../addons/__SITE_REF__/modules/',
    SHARED_ADDONPATH.'modules/' => '../../../addons/shared_addons/modules/'
);

/* End of file config.php */

